# Generated by Django 3.1.4 on 2021-01-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0002_auto_20210104_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='wishes',
            field=models.ManyToManyField(blank=True, to='wish.Wish'),
        ),
    ]
