# Generated by Django 3.1.4 on 2021-01-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish', '0003_auto_20210104_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Wish', 'verbose_name_plural': 'Wishes'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wish List', 'verbose_name_plural': 'Wish Lists'},
        ),
    ]
