# Generated by Django 3.1.4 on 2021-01-04 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210104_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='user_id',
            new_name='user',
        ),
    ]
